### ISSUE TITLE
payloads can't be type function

### ISSUE THREAD

**Issue by PatrickJS** [ajoslin/app-bridge#1]
maybe this should be documented

**Comment by ajoslin** [comment]
Ah, that damn optional argument check.  https://github.com/ajoslin/app-bridge/blob/master/index.js#L40

That can be changed to `if (typeof payload === 'function' && !callback)`.

PR welcome.

**Comment by PatrickJS** [comment]
done via https://github.com/ajoslin/app-bridge/pull/2
